// <auto-generated>
// Generated by scripts/gen-response-reader.py. Do not edit by hand.
// Regenerate after adding or removing a *Response.cs message type.
// </auto-generated>
#if !NET7_0_OR_GREATER
namespace Dekaf.Protocol;

/// <summary>
/// ApiKey-keyed response reader used on target frameworks that do not support
/// static abstract interface members (netstandard2.0/2.1). Mirrors the
/// static-abstract <c>IKafkaResponse.Read</c> dispatch used on net7.0+.
/// </summary>
internal static class GeneratedResponseReader
{
    public static IKafkaResponse Read(ApiKey apiKey, ref KafkaProtocolReader reader, short version)
        => apiKey switch
        {
            ApiKey.AddOffsetsToTxn => AddOffsetsToTxnResponse.Read(ref reader, version),
            ApiKey.AddPartitionsToTxn => AddPartitionsToTxnResponse.Read(ref reader, version),
            ApiKey.AlterClientQuotas => AlterClientQuotasResponse.Read(ref reader, version),
            ApiKey.AlterConfigs => AlterConfigsResponse.Read(ref reader, version),
            ApiKey.AlterPartitionReassignments => AlterPartitionReassignmentsResponse.Read(ref reader, version),
            ApiKey.AlterShareGroupOffsets => AlterShareGroupOffsetsResponse.Read(ref reader, version),
            ApiKey.AlterUserScramCredentials => AlterUserScramCredentialsResponse.Read(ref reader, version),
            ApiKey.ApiVersions => ApiVersionsResponse.Read(ref reader, version),
            ApiKey.ConsumerGroupDescribe => ConsumerGroupDescribeResponse.Read(ref reader, version),
            ApiKey.ConsumerGroupHeartbeat => ConsumerGroupHeartbeatResponse.Read(ref reader, version),
            ApiKey.CreateAcls => CreateAclsResponse.Read(ref reader, version),
            ApiKey.CreateDelegationToken => CreateDelegationTokenResponse.Read(ref reader, version),
            ApiKey.CreatePartitions => CreatePartitionsResponse.Read(ref reader, version),
            ApiKey.CreateTopics => CreateTopicsResponse.Read(ref reader, version),
            ApiKey.DeleteAcls => DeleteAclsResponse.Read(ref reader, version),
            ApiKey.DeleteGroups => DeleteGroupsResponse.Read(ref reader, version),
            ApiKey.DeleteRecords => DeleteRecordsResponse.Read(ref reader, version),
            ApiKey.DeleteShareGroupOffsets => DeleteShareGroupOffsetsResponse.Read(ref reader, version),
            ApiKey.DeleteTopics => DeleteTopicsResponse.Read(ref reader, version),
            ApiKey.DescribeAcls => DescribeAclsResponse.Read(ref reader, version),
            ApiKey.DescribeClientQuotas => DescribeClientQuotasResponse.Read(ref reader, version),
            ApiKey.DescribeConfigs => DescribeConfigsResponse.Read(ref reader, version),
            ApiKey.DescribeDelegationToken => DescribeDelegationTokenResponse.Read(ref reader, version),
            ApiKey.DescribeGroups => DescribeGroupsResponse.Read(ref reader, version),
            ApiKey.DescribeLogDirs => DescribeLogDirsResponse.Read(ref reader, version),
            ApiKey.DescribeProducers => DescribeProducersResponse.Read(ref reader, version),
            ApiKey.DescribeShareGroupOffsets => DescribeShareGroupOffsetsResponse.Read(ref reader, version),
            ApiKey.DescribeTopicPartitions => DescribeTopicPartitionsResponse.Read(ref reader, version),
            ApiKey.DescribeTransactions => DescribeTransactionsResponse.Read(ref reader, version),
            ApiKey.DescribeUserScramCredentials => DescribeUserScramCredentialsResponse.Read(ref reader, version),
            ApiKey.ElectLeaders => ElectLeadersResponse.Read(ref reader, version),
            ApiKey.EndTxn => EndTxnResponse.Read(ref reader, version),
            ApiKey.ExpireDelegationToken => ExpireDelegationTokenResponse.Read(ref reader, version),
            ApiKey.Fetch => FetchResponse.Read(ref reader, version),
            ApiKey.FindCoordinator => FindCoordinatorResponse.Read(ref reader, version),
            ApiKey.GetTelemetrySubscriptions => GetTelemetrySubscriptionsResponse.Read(ref reader, version),
            ApiKey.IncrementalAlterConfigs => IncrementalAlterConfigsResponse.Read(ref reader, version),
            ApiKey.InitProducerId => InitProducerIdResponse.Read(ref reader, version),
            ApiKey.ListGroups => ListGroupsResponse.Read(ref reader, version),
            ApiKey.ListOffsets => ListOffsetsResponse.Read(ref reader, version),
            ApiKey.ListPartitionReassignments => ListPartitionReassignmentsResponse.Read(ref reader, version),
            ApiKey.ListTransactions => ListTransactionsResponse.Read(ref reader, version),
            ApiKey.Metadata => MetadataResponse.Read(ref reader, version),
            ApiKey.OffsetCommit => OffsetCommitResponse.Read(ref reader, version),
            ApiKey.OffsetDelete => OffsetDeleteResponse.Read(ref reader, version),
            ApiKey.OffsetFetch => OffsetFetchResponse.Read(ref reader, version),
            ApiKey.OffsetForLeaderEpoch => OffsetForLeaderEpochResponse.Read(ref reader, version),
            ApiKey.Produce => ProduceResponse.Read(ref reader, version),
            ApiKey.PushTelemetry => PushTelemetryResponse.Read(ref reader, version),
            ApiKey.RenewDelegationToken => RenewDelegationTokenResponse.Read(ref reader, version),
            ApiKey.SaslAuthenticate => SaslAuthenticateResponse.Read(ref reader, version),
            ApiKey.SaslHandshake => SaslHandshakeResponse.Read(ref reader, version),
            ApiKey.ShareAcknowledge => ShareAcknowledgeResponse.Read(ref reader, version),
            ApiKey.ShareFetch => ShareFetchResponse.Read(ref reader, version),
            ApiKey.ShareGroupDescribe => ShareGroupDescribeResponse.Read(ref reader, version),
            ApiKey.ShareGroupHeartbeat => ShareGroupHeartbeatResponse.Read(ref reader, version),
            ApiKey.TxnOffsetCommit => TxnOffsetCommitResponse.Read(ref reader, version),
            ApiKey.UpdateFeatures => UpdateFeaturesResponse.Read(ref reader, version),
            _ => throw new System.NotSupportedException(
                $"No response reader is registered for API key {apiKey}."),
        };
}
#endif
