#!/usr/bin/env python3
"""Generates GeneratedResponseReader.cs: an ApiKey-keyed switch that calls each
concrete <X>Response.Read(ref reader, version).

On net7.0+ the connection dispatch uses the static-abstract IKafkaResponse.Read
directly, so this generated switch is only compiled for the netstandard TFMs
(guarded by #if !NET7_0_OR_GREATER). The switch is required because the Read
method takes a `ref KafkaProtocolReader` (a ref struct), which cannot be invoked
through reflection or a delegate on those TFMs.

Run from the repo root:  python scripts/gen-response-reader.py
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MESSAGES = REPO / "src" / "Dekaf" / "Protocol" / "Messages"
OUT = REPO / "src" / "Dekaf" / "Protocol" / "GeneratedResponseReader.cs"

CLASS_RE = re.compile(r"class\s+(\w+)\s*:\s*[^{]*\bIKafkaResponse\b")
APIKEY_RE = re.compile(r"public\s+static\s+ApiKey\s+ApiKey\s*=>\s*ApiKey\.(\w+)\s*;")


def main() -> int:
    entries: dict[str, str] = {}
    for path in sorted(MESSAGES.rglob("*Response.cs")):
        text = path.read_text(encoding="utf-8")
        cls = CLASS_RE.search(text)
        key = APIKEY_RE.search(text)
        if not cls or not key:
            print(f"WARN: could not parse {path.name} "
                  f"(class={bool(cls)}, apiKey={bool(key)})", file=sys.stderr)
            continue
        api = key.group(1)
        if api in entries and entries[api] != cls.group(1):
            print(f"ERROR: duplicate ApiKey.{api}: "
                  f"{entries[api]} vs {cls.group(1)}", file=sys.stderr)
            return 1
        entries[api] = cls.group(1)

    cases = "\n".join(
        f"            ApiKey.{api} => {cls}.Read(ref reader, version),"
        for api, cls in sorted(entries.items())
    )

    content = f"""// <auto-generated>
// Generated by scripts/gen-response-reader.py. Do not edit by hand.
// Regenerate after adding or removing a *Response.cs message type.
// </auto-generated>
#if !NET7_0_OR_GREATER
using Dekaf.Protocol.Messages;

namespace Dekaf.Protocol;

/// <summary>
/// ApiKey-keyed response reader used on target frameworks that do not support
/// static abstract interface members (netstandard2.0/2.1). Mirrors the
/// static-abstract <c>IKafkaResponse.Read</c> dispatch used on net7.0+.
/// </summary>
internal static class GeneratedResponseReader
{{
    public static IKafkaResponse Read(ApiKey apiKey, ref KafkaProtocolReader reader, short version)
        => apiKey switch
        {{
{cases}
            _ => throw new System.NotSupportedException(
                $"No response reader is registered for API key {{apiKey}}."),
        }};
}}
#endif
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} with {len(entries)} response readers.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
